name: SVG Generate CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
          npm install

    - name: Update game.svg
      run: node index.js
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '40774281+ViniciusFXavier@users.noreply.github.com'
          git commit -am "BOT: update game.svg automatically"
          git push